# Generated by Django 6.0.7 on 2026-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partido",
            name="goles_local",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partido",
            name="goles_visitante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
