# Generated by Django 6.0.7 on 2026-07-30 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jugador',
            name='unico_jugador_por_equipo',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
