# Generated by Django 6.0.7 on 2026-07-30 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0002_remove_jugador_unico_jugador_por_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='liga',
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='matches.categoria'),
            preserve_default=False,
        ),
    ]
