# Generated by Django 6.0.7 on 2026-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("capitan", "Capitán"),
                    ("jugador", "Jugador"),
                ],
                default="jugador",
                max_length=10,
            ),
        ),
    ]
