# Generated by Django 6.0.7 on 2026-07-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liga",
            name="cupos_maximos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="liga",
            name="formato",
            field=models.CharField(
                choices=[
                    ("liga", "Liga (ida y vuelta)"),
                    ("liguilla", "Liguilla (una vuelta + eliminatorias)"),
                ],
                default="liga",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="liga",
            name="sede",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
